version: '3'
services:
  db:
    container_name: wp-msql
    ports:
      - "3307:3306"
    image: 'mysql'
    environment:
       MYSQL_ROOT_PASSWORD: 12345678
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
    networks:
      - my_net
networks:
  my_net: