version: '3'
services:
  db:
    container_name: my-msql
    ports:
      - "3307:3306"
    image: 'mysql'
    volumes:
       - $PWD/data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: 12345678
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
    networks:
      - my_net

  wp:
    container_name: wp-web
    depends_on:
      - db
    image: wordpress
    ports:
      - "80:80"
    volumes:
      - $PWD/html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - my_net

networks:
  my_net: